/**
 * @omnichannel/tsparser
 *
 * TypeScript AST parser and code generator from JSON.
 *
 * This library receives a JSON representation of TypeScript AST nodes
 * (generated by pyastts) and converts them to actual TypeScript code.
 *
 * @example
 * ```typescript
 * import { parseAndPrint, deserialize, printNode } from '@omnichannel/tsparser';
 *
 * // From JSON string
 * const json = '{"type": "factory", "name": "createIdentifier", "args": [...]}';
 * const code = parseAndPrint(json);
 * console.log(code); // Outputs TypeScript code
 *
 * // From parsed object
 * const node = deserialize(parsedJson);
 * const code = printNode(node);
 * ```
 */

import ts from 'typescript';
import {
    SerializedNode,
    SerializedFactory,
    SerializedLiteral,
    SerializedUndefined,
    SerializedNumber,
    isLiteral,
    isNumber,
    isFactory,
} from './types.js';
import {
    deserialize,
    deserializeStatement,
    deserializeStatements,
    deserializeExpression,
    deserializeDeclaration,
} from './deserializer.js';
import {
    printNode,
    printNodes,
    printFile,
    printNodeList,
    PrinterOptions,
} from './printer.js';

// Re-export types
export type {
    SerializedNode,
    SerializedFactory,
    SerializedLiteral,
    SerializedUndefined,
    SerializedNumber,
    PrinterOptions,
};

// Re-export type guards
export { isLiteral, isNumber, isFactory };

// Re-export deserializer functions
export {
    deserialize,
    deserializeStatement,
    deserializeStatements,
    deserializeExpression,
    deserializeDeclaration,
};

// Re-export printer functions
export { printNode, printNodes, printFile, printNodeList };

/**
 * Parses a JSON string and deserializes it to a TypeScript AST node.
 */
export function parse(json: string): ts.Node {
    const data = JSON.parse(json) as SerializedNode;
    return deserialize(data) as ts.Node;
}

/**
 * Parses a JSON string, deserializes it, and prints it as TypeScript code.
 */
export async function parseAndPrint(
    json: string,
    options: PrinterOptions = {}
): Promise<string> {
    const node = parse(json);
    return await printNode(node, options);
}

/**
 * Parses multiple JSON objects and prints them as a TypeScript file.
 */
export async function parseAndPrintFile(
    jsonNodes: string[],
    options: PrinterOptions = {}
): Promise<string> {
    const statements = jsonNodes.map((json) => {
        const data = JSON.parse(json) as SerializedNode;
        return deserializeStatement(data);
    });
    return await printFile(statements, options);
}

/**
 * Converts a serialized node object directly to TypeScript code.
 */
export async function toTypeScript(
    node: SerializedNode,
    options: PrinterOptions = {}
): Promise<string> {
    const tsNode = deserialize(node) as ts.Node;
    return await printNode(tsNode, options);
}

/**
 * Converts multiple serialized node objects to a TypeScript file.
 */
export async function toTypeScriptFile(
    nodes: SerializedNode[],
    options: PrinterOptions = {}
): Promise<string> {
    const statements = nodes.map(
        (node) => deserialize(node) as ts.Statement
    );
    return await printFile(statements, options);
}
